## Config file

# Log 
seed: 777
use_cuda: 1           # 1 for True, 0 for False

# dataset
speaker_no: 2

noise_direc: data/noise/
reference_direc: data/LibriSpeech_sim/
mix_lst_path: data/LibriSpeech_sex_spa/sex_spa.csv  
audio_direc: data/LibriSpeech_sex_spa/

audio_sr: 16000


# dataloader
num_workers: 8
batch_size: 16         # 2-GPU training with a total effective batch size of 16
accu_grad: 0
effec_batch_size: 4   # per GPU, only used if accu_grad is set to 1, must be multiple times of batch size
max_length: 6         # truncate the utterances in dataloader, in seconds 

# network settings
init_from: None       # 'None' or a log name 'log_2024-07-22(18:12:13)'
causal: 0             # 1 for True, 0 for False
network_reference:
  cue: text            
  backbone: roberta  
  emb_size: 256      
network_audio:
  backbone: ss_dprnn
  N: 256
  L: 40
  B: 64
  H: 128
  K: 100
  R: 6

# optimizer
loss_type: sisdr      # "snr", "sisdr", "hybrid"
init_learning_rate: 0.0001
max_epoch: 150
clip_grad_norm: 5
